# ISLP page 52-77 exercise


In [1]:
import numpy as np

In [2]:
x = np.array([3,4,5])
y = np.array([4,9,7])
x + y

array([ 7, 13, 12])

In [3]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [4]:
x.ndim

2

In [5]:
x.dtype

dtype('int64')

In [6]:
np.array([[1,2],[3.0,4]]).dtype

dtype('float64')

In [7]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [8]:
x.shape

(2, 2)

In [9]:
x = np.array([1, 2, 3, 4])
x.sum()

10

In [10]:
x = np.array([1,2,3,4,5,6])
print("beginning x:\n", x)
x_reshape = x.reshape((2,3))
print("reshaped x: \n", x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x: 
 [[1 2 3]
 [4 5 6]]


In [11]:
x_reshape[0, 0]

1

In [12]:
x_reshape[1, 2]

6

In [13]:
print("x before we modify x_reshape:\n", x)
print("x_reshape before we modify x_reshape:\n", x_reshape)
x_reshape[0, 0] = 5
print("x_reshape after we modify its top left element:\n", x_reshape)
print("x after we modify top left element of x_reshape:\n", x)

x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


In [14]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [15]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [16]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [17]:
x**2

array([25,  4,  9, 16, 25, 36])

In [18]:
x**0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [19]:
x = np.random.normal(size=50)
x

array([ 0.57507619,  0.81524866,  0.65233235, -0.01603551, -0.83390878,
       -0.05341095, -0.93304478,  0.4420312 , -1.38272875, -0.34405083,
        1.05710124, -0.27216873,  1.96048771, -1.22824352, -1.14645582,
        0.96098952,  2.15145595,  0.38661389,  0.37932297, -0.66452317,
        1.45486548, -0.53886974, -1.07895685, -0.75081979,  0.58938305,
       -1.46124709,  0.56127535,  0.41637515,  0.61490122,  0.25990253,
        0.09037061, -0.91152099, -1.94900303, -0.31172342,  1.46739559,
        0.15478949, -0.89946335, -0.24230573, -0.14866457, -0.30951311,
        1.58440175, -0.62574523, -1.34760397, -0.12807348,  0.88979067,
        1.3229761 ,  0.83609567, -0.98651911, -0.23776053,  0.13383529])

In [20]:
y = x + np.random.normal(loc=50,scale=1,size=50)


In [21]:
np.corrcoef(x,y)

array([[1.        , 0.67934611],
       [0.67934611, 1.        ]])

In [23]:
print(np.random.normal(scale=5,size=2))
print(np.random.normal(scale=5,size=2))
print(np.random.normal(scale=5,size=2))
print(np.random.normal(scale=5,size=2))
print(np.random.normal(scale=5,size=2))
print(np.random.normal(scale=5,size=2))
print(np.random.normal(scale=5,size=2))

[-2.64285571 -0.40204105]
[0.10149752 3.07416742]
